import Head from "next/head";
import Image from "next/image";
import {useCharacters} from '@/assets/hooks/useCharacters';



export default function Characters() {
const characters = useCharacters()

  return (
    <>
      <Head>
        <title>LENA Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
            {characters &&  characters.map(ch =>(
                <div key={ch.id}>
                    <div>{ch.name}</div>
                    <Image src={ch.image} alt={`picture of ${ch.name}`} width={300} height={300}/>
                </div>
            ))}
        </main>
    </>
  );
}
