import Head from "next/head";
import {useCharacters} from '@/assets/hooks/useCharacters';
import {CharacterCard} from '@/components/CharacterCard/CharacterCard';
import styles from "@/styles/Home.module.css";


export default function Characters() {
const characters = useCharacters()

  return (
    <>
      <Head>
        <title>LENA Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
            {characters &&  characters.map(char =>(
                <CharacterCard key={char.id} char={char}/>
            ))}
        </main>
    </>
  );
}
